remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "What do I want to eat?"
description: "menu planning"
author:
  name: "Kelley Bonneville"

# Do not change the following line.
  copyright: true
